version: "2"
services:
  twitter-app:
    container_name: Twitter-botnet
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"


